### ISSUE TITLE
FR: Additional Battery Packs

### ISSUE THREAD

**Issue by kaybasket** [Psynosaur/esphome-deye-bms#6]
Hi,

I do have 10 Battery Packs (AI-W5.1-B) do you have a configuration available which can handle up to 10 battery packs?
If not, i'll try to collect all relevant InterCAN registers.

thanks & BR

**Comment by Psynosaur** [comment]
Hi

```yaml
###########################################################################################################
# Pack 3: CAN bus frames
###########################################################################################################
- can_id: 0x02098003
  use_extended_id: true
  then:
    - lambda: |-
        float high_cell = ((x[0] << 8) | x[1]) / 1000.0;
        id(pack_3_cell_high_voltage).publish_state(high_cell);
        int high_position = x[2];
        id(pack_3_cell_h).publish_state(std::to_string(high_position).c_str());
        float low_cell = ((x[3] << 8) | x[4]) / 1000.0;
        id(pack_3_cell_low_voltage).publish_state(low_cell);
        int low_position = x[5];
        id(pack_3_cell_l).publish_state(std::to_string(low_position).c_str());

- can_id: 0x04008003
  use_extended_id: true
  then:
    - lambda: |-
        float cell_01 = ((x[0] << 8) | x[1]) / 1000.0;
        id(pack_3_cell_01_voltage).publish_state(cell_01);
        float cell_02 = ((x[2] << 8) | x[3]) / 1000.0;
        id(pack_3_cell_02_voltage).publish_state(cell_02);
        float cell_03 = ((x[4] << 8) | x[5]) / 1000.0;
        id(pack_3_cell_03_voltage).publish_state(cell_03);
        float cell_04 = ((x[6] << 8) | x[7]) / 1000.0;
        id(pack_3_cell_04_voltage).publish_state(cell_04);

- can_id: 0x04018003
  use_extended_id: true
  then:
    - lambda: |-
        float cell_05 = ((x[0] << 8) | x[1]) / 1000.0;
        id(pack_3_cell_05_voltage).publish_state(cell_05);
        float cell_06 = ((x[2] << 8) | x[3]) / 1000.0;
        id(pack_3_cell_06_voltage).publish_state(cell_06);
        float cell_07 = ((x[4] << 8) | x[5]) / 1000.0;
        id(pack_3_cell_07_voltage).publish_state(cell_07);
        float cell_08 = ((x[6] << 8) | x[7]) / 1000.0;
        id(pack_3_cell_08_voltage).publish_state(cell_08);

- can_id: 0x04028003
  use_extended_id: true
  then:
    - lambda: |-
        float cell_09 = ((x[0] << 8) | x[1]) / 1000.0;
        id(pack_3_cell_09_voltage).publish_state(cell_09);
        float cell_10 = ((x[2] << 8) | x[3]) / 1000.0;
        id(pack_3_cell_10_voltage).publish_state(cell_10);
        float cell_11 = ((x[4] << 8) | x[5]) / 1000.0;
        id(pack_3_cell_11_voltage).publish_state(cell_11);
        float cell_12 = ((x[6] << 8) | x[7]) / 1000.0;
        id(pack_3_cell_12_voltage).publish_state(cell_12);

- can_id: 0x04038003
  use_extended_id: true
  then:
    - lambda: |-
        float cell_13 = ((x[0] << 8) | x[1]) / 1000.0;
        id(pack_3_cell_13_voltage).publish_state(cell_13);
        float cell_14 = ((x[2] << 8) | x[3]) / 1000.0;
        id(pack_3_cell_14_voltage).publish_state(cell_14);
        float cell_15 = ((x[4] << 8) | x[5]) / 1000.0;
        id(pack_3_cell_15_voltage).publish_state(cell_15);
        float cell_16 = ((x[6] << 8) | x[7]) / 1000.0;
        id(pack_3_cell_16_voltage).publish_state(cell_16);

###########################################################################################################
# Pack 3: Template Sensors
###########################################################################################################
- platform: template
  name: "Pack 3: Cell_high"
  id: "pack_3_cell_high_voltage"
  unit_of_measurement: 'V'
  device_class: voltage
  state_class: measurement
  accuracy_decimals: 3

- platform: template
  name: "Pack 3: Cell_low"
  id: "pack_3_cell_low_voltage"
  unit_of_measurement: 'V'
  device_class: voltage
  state_class: measurement
  accuracy_decimals: 3

- platform: template
  name: "Pack 3: Cell_01"
  id: "pack_3_cell_01_voltage"
  unit_of_measurement: 'V'
  device_class: voltage
  state_class: measurement
  accuracy_decimals: 3

- platform: template
  name: "Pack 3: Cell_02"
  id: "pack_3_cell_02_voltage"
  unit_of_measurement: 'V'
  device_class: voltage
  state_class: measurement
  accuracy_decimals: 3

- platform: template
  name: "Pack 3: Cell_03"
  id: "pack_3_cell_03_voltage"
  unit_of_measurement: 'V'
  device_class: voltage
  state_class: measurement
  accuracy_decimals: 3

- platform: template
  name: "Pack 3: Cell_04"
  id: "pack_3_cell_04_voltage"
  unit_of_measurement: 'V'
  device_class: voltage
  state_class: measurement
  accuracy_decimals: 3

- platform: template
  name: "Pack 3: Cell_05"
  id: "pack_3_cell_05_voltage"
  unit_of_measurement: 'V'
  device_class: voltage
  state_class: measurement
  accuracy_decimals: 3

- platform: template
  name: "Pack 3: Cell_06"
  id: "pack_3_cell_06_voltage"
  unit_of_measurement: 'V'
  device_class: voltage
  state_class: measurement
  accuracy_decimals: 3

- platform: template
  name: "Pack 3: Cell_07"
  id: "pack_3_cell_07_voltage"
  unit_of_measurement: 'V'
  device_class: voltage
  state_class: measurement
  accuracy_decimals: 3

- platform: template
  name: "Pack 3: Cell_08"
  id: "pack_3_cell_08_voltage"
  unit_of_measurement: 'V'
  device_class: voltage
  state_class: measurement
  accuracy_decimals: 3

- platform: template
  name: "Pack 3: Cell_09"
  id: "pack_3_cell_09_voltage"
  unit_of_measurement: 'V'
  device_class: voltage
  state_class: measurement
  accuracy_decimals: 3

- platform: template
  name: "Pack 3: Cell_10"
  id: "pack_3_cell_10_voltage"
  unit_of_measurement: 'V'
  device_class: voltage
  state_class: measurement
  accuracy_decimals: 3

- platform: template
  name: "Pack 3: Cell_11"
  id: "pack_3_cell_11_voltage"
  unit_of_measurement: 'V'
  device_class: voltage
  state_class: measurement
  accuracy_decimals: 3

- platform: template
  name: "Pack 3: Cell_12"
  id: "pack_3_cell_12_voltage"
  unit_of_measurement: 'V'
  device_class: voltage
  state_class: measurement
  accuracy_decimals: 3

- platform: template
  name: "Pack 3: Cell_13"
  id: "pack_3_cell_13_voltage"
  unit_of_measurement: 'V'
  device_class: voltage
  state_class: measurement
  accuracy_decimals: 3

- platform: template
  name: "Pack 3: Cell_14"
  id: "pack_3_cell_14_voltage"
  unit_of_measurement: 'V'
  device_class: voltage
  state_class: measurement
  accuracy_decimals: 3

- platform: template
  name: "Pack 3: Cell_15"
  id: "pack_3_cell_15_voltage"
  unit_of_measurement: 'V'
  device_class: voltage
  state_class: measurement
  accuracy_decimals: 3

- platform: template
  name: "Pack 3: Cell_16"
  id: "pack_3_cell_16_voltage"
  unit_of_measurement: 'V'
  device_class: voltage
  state_class: measurement
  accuracy_decimals: 3
```

To create Packs 4 through 10, simply replicate the above blocks with the following adjustments:

CAN Bus Frames:
– Change the CAN IDs by replacing the pack number. For example, for Pack 4 use:
• High/Low frame: 0x02098004
• Cell group frames: 0x04008004, 0x04018004, 0x04028004, and 0x04038004
– Similarly, for Pack 5 use 0x02098005 (and so on).
– For Pack 10 use hexadecimal “0A” (i.e. 0x0209800A, 0x0400800A, …) and for Pack 11 use “0B”.

Template Sensor IDs and Names:
– Replace every instance of “pack_3_” with “pack_4_”, “pack_5_”, etc., and update the sensor names accordingly (e.g. “Pack 4: Cell_01”, …).

By following the pattern in the Pack 3 example, you can generate the complete configuration for all other additional packs.

cheers
